### PR TITLE
refactor: convert to antd components

### PR DESCRIPTION
**Pull request by aeng**
Convert to UI library from bootstrap to ant.design. No changes in UX apart from top menu now becoming sidebar.

### CODE REVIEW

**Comment by efloden** [comment]
:lgtm:

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[frontend/src/app/components/Alert/index.tsx, line 4 at r1](https://beta.reviewable.io/reviews/zanata/zanata-mt/62#-LAM2eEb3In6K9N8qjN_:-LAM2eEb3In6K9N8qjNa:b-o5mds8) ([raw file](https://github.com/zanata/zanata-mt/blob/d9ffc3764a73888ff2e85feb70dde2e8ea711f99/frontend/src/app/components/Alert/index.tsx#L4)):*
> ```XML
> import { MSG_TYPE } from '../../constants/actions'
> import {ErrorData} from '../../types/models'
> import { Alert as AntdAlert } from 'antd'
> ```

This looks much simpler, can hopefully start using it for notifications in the React Editor as well.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-mt/62#-:-LAM3F_y3kvbWQ13jh4s:bnfp4nl)*

**Comment by djansen-redhat** [comment]
classname ant-col-8 used for the info panel needlessly crushes the info into 33% of the available space.

**Comment by djansen-redhat** [comment]
Codecov is wrong
Codacy, I don't know. Missing semi-colons in import statements?

**Comment by seanf** [comment]
@aeng @djansen-redhat I've disabled the tslint patterns in codacy for double quotes and semi-colons.

**Comment by djansen-redhat** [comment]
Thanks @seanf

**Pull request merged**
