### PR TITLE
Jenkinsfile - perform release if commit to master branch

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1832

Update of jenkinsfile
```
-> commit to branch -> maven build
-> commit to master -> maven build and release 
     (parallel) maven site
     (parallel) docker image build -> deploy docker registry -> deploy to stage (openshift)
     -> Pending user input before deploy to PROD
```

Can disable job ZanataMT-site,  ZanataMT-release-STAGE, ZanataMT-release-PROD after this merge. All testing on PR should be done via local docker build.

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/20)

### CODE REVIEW

**Comment by aeng** [comment]
Build on master branch: https://zanata-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/github-zanata-org/job/zanata-mt/view/change-requests/job/PR-20/124

**Comment by huangp** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/docker/Dockerfile-OPENSHIFT, line 25 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/20#-KnrRj3yzDz-us0u9bB5:-KnrRj3yzDz-us0u9bB6:bgatdxh) ([raw file](https://github.com/zanata/zanata-mt/blob/abc79f2e3aa979f4f60e31c70afed68b922bd009/server/docker/Dockerfile-OPENSHIFT#L25)):*
> ```
> # copy war file
> # assuming war file is in the same directory
> ADD ROOT.war $JBOSS_HOME/standalone/deployments/ROOT.war
> ```

You should use COPY here instead of ADD. ADD will unzip the archive... unless that's your intention.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/20)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/docker/Dockerfile-OPENSHIFT, line 25 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/20#-KnrRj3yzDz-us0u9bB5:-KnrUFVnQ9oYwKT0Qp7i:b-896fix) ([raw file](https://github.com/zanata/zanata-mt/blob/abc79f2e3aa979f4f60e31c70afed68b922bd009/server/docker/Dockerfile-OPENSHIFT#L25)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

You should use COPY here instead of ADD. ADD will unzip the archive... unless that's your intention.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/20)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/20#-:-KnrbLvkxYbLIloSSVLm:b-ew2adl)*

**Pull request merged**
