### PR TITLE
Retry 3 times for postgre downloading

### PR DESCRIPTION
**Pull request by definite**
https://zanata.atlassian.net/browse/ZNTAMT-18

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/52)

### CODE REVIEW

**Comment by aeng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/Dockerfile, line 9 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/52#-L36WFrFUvOpiqlwAfXM:-L36WFrGbZWh3hjr8q2G:b57o922) ([raw file](https://github.com/zanata/zanata-mt/blob/89cf16f830dc8f7db6cd38f91a928d573751a892/server/Dockerfile#L9)):*
> ```Dockerfile
> 
> # Install postgresql driver
> RUN curl --retry 3 -L -o $JBOSS_HOME/standalone/deployments/postgresql-connector.jar https://repo1.maven.org/maven2/org/postgresql/postgresql/9.4.1212/postgresql-9.4.1212.jar
> ```

Do we know why it failed the first time?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/52)*

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/52)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/52#-:-L36WM08moHiK5XA5As7:bnfp4nl)*

**Comment by definite** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/Dockerfile, line 9 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/52#-L36WFrFUvOpiqlwAfXM:-L36Y_hvILd8V5qYIR1R:bmkal4o) ([raw file](https://github.com/zanata/zanata-mt/blob/89cf16f830dc8f7db6cd38f91a928d573751a892/server/Dockerfile#L9)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Do we know why it failed the first time?
</blockquote></details>

It is a timeout.  retry may help if the file to be download is cached (transparent proxies, perhaps).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/52)*

**Comment by definite** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/52)*

**Pull request merged**
