### PR TITLE
Convert frontend to TypeScript

### PR DESCRIPTION
**Pull request by aeng**
This PR only include new frontend with Typescript implementation. It does not change any backend functionalities.

### CODE REVIEW

**Comment by efloden** [comment]
Reviewed 15 of 56 files at r1, 2 of 19 files at r2, 10 of 71 files at r3.
Review status: 27 of 75 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/57)*

**Comment by seanf** [comment]
@aeng It looks like the JS/TS code isn't set up to run Jest yet (nor to gather coverage).

---

Review status: 27 of 75 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/57#-:-L6QAWSfj4nQzz1UHNT1:b-3yfafx)*

**Comment by aeng** [comment]
yeah its not. Trying not to overblow this PR

---

Review status: 27 of 75 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/57#-:-L6USU-qwLFkRXF2dLYC:b-40zuwi)*

**Comment by efloden** [comment]
Reviewed 60 of 71 files at r3, 1 of 1 files at r4, 1 of 2 files at r5.
Review status: 75 of 76 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[frontend/src/package.json, line 69 at r4](https://beta.reviewable.io/reviews/zanata/zanata-mt/57#-L6Z1okF4Uq4TNP_fNan:-L6Z1okF4Uq4TNP_fNao:b-8fx2u7) ([raw file](https://github.com/zanata/zanata-mt/blob/f2c0a32490ec5aed2f30e840253ddda2e32b1874/frontend/src/package.json#L69)):*
> ```JSON
>     "moment-timezone": "0.5.14",
>     "prop-types": "15.6.0",
>     "react": "16.2.0",
> ```

:+1: 

---

*[frontend/src/tsconfig.json, line 9 at r4](https://beta.reviewable.io/reviews/zanata/zanata-mt/57#-L6YyzbV3wvir3xy-nNb:-L6YyzbV3wvir3xy-nNc:berxy0m) ([raw file](https://github.com/zanata/zanata-mt/blob/f2c0a32490ec5aed2f30e840253ddda2e32b1874/frontend/src/tsconfig.json#L9)):*
> ```JSON
>     "importHelpers": true,
>     "sourceMap": true,
>     "target": "es5",
> ```

Why not target ESNext for a new project?

---

*[frontend/src/webpack.config.js, line 122 at r4](https://beta.reviewable.io/reviews/zanata/zanata-mt/57#-L6Yzc3w52MI-PaU9N7g:-L6Yzc3w52MI-PaU9N7h:bkw8sqi) ([raw file](https://github.com/zanata/zanata-mt/blob/f2c0a32490ec5aed2f30e840253ddda2e32b1874/frontend/src/webpack.config.js#L122)):*
> ```JavaScript
>     isProd
>       ? undefined
>       : new Webpack.optimize.CommonsChunkPlugin({
> ```

We could avoid some of the confusion around CommonChunkPlugin and possibly have faster builds by using Webpack 4 - worth trying?

---

*[frontend/src/app/index.tsx, line 51 at r4](https://beta.reviewable.io/reviews/zanata/zanata-mt/57#-L6Z-LDF706FmUeAszso:-L6Z-LDG9YW3J4k1T6hA:b-oyhj2o) ([raw file](https://github.com/zanata/zanata-mt/blob/f2c0a32490ec5aed2f30e840253ddda2e32b1874/frontend/src/app/index.tsx#L51)):*
> ```XML
>   <Provider store={store}>
>     <Router history={history}>
>       <div>
> ```

Is this div necessary? 

---

*[frontend/src/app/actions/info.ts, line 17 at r4](https://beta.reviewable.io/reviews/zanata/zanata-mt/57#-L6YthZz5unwYKn93kmG:-L6YthZz5unwYKn93kmH:b-ddrab6) ([raw file](https://github.com/zanata/zanata-mt/blob/f2c0a32490ec5aed2f30e840253ddda2e32b1874/frontend/src/app/actions/info.ts#L17)):*
> ```XML
>   const endpoint = API_URL + '/info'
>   const apiTypes = [
>     Actions.GET_INFO_REQUEST,
> ```

We use a tuple type for actions that looks like `export type APITypes = [string|{}, string|{}, string|{}]` in [Zanata Platform PR 737](https://github.com/zanata/zanata-platform/pull/737/files#diff-328ae56e88f06e81ee08e844404fd6b0), defining each actions type individually like this seems like a good approach as well.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-mt/57)*

**Comment by efloden** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/57)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[frontend/src/tsconfig.json, line 9 at r4](https://reviewable.io:443/reviews/zanata/zanata-mt/57#-L6YyzbV3wvir3xy-nNb:-L6Z4j9UXq7Tuby9gXDR:bnnbdbs) ([raw file](https://github.com/zanata/zanata-mt/blob/f2c0a32490ec5aed2f30e840253ddda2e32b1874/frontend/src/tsconfig.json#L9)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

Why not target ESNext for a new project?
</blockquote></details>

Trying to target somewhat standard version. ESNext is nice but I think too new to and not stabilised yet. 

---

*[frontend/src/webpack.config.js, line 122 at r4](https://reviewable.io:443/reviews/zanata/zanata-mt/57#-L6Yzc3w52MI-PaU9N7g:-L6Z6GfdM8hIMKe0lxUX:b-vwpq20) ([raw file](https://github.com/zanata/zanata-mt/blob/f2c0a32490ec5aed2f30e840253ddda2e32b1874/frontend/src/webpack.config.js#L122)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

We could avoid some of the confusion around CommonChunkPlugin and possibly have faster builds by using Webpack 4 - worth trying?
</blockquote></details>

Possibly. I think best to have it as separate PR unless I can migrate to webpack 4 in time. 

---

*[frontend/src/app/index.tsx, line 51 at r4](https://reviewable.io:443/reviews/zanata/zanata-mt/57#-L6Z-LDF706FmUeAszso:-L6Z5raw0AV12eqnNGSy:b-a1xt35) ([raw file](https://github.com/zanata/zanata-mt/blob/f2c0a32490ec5aed2f30e840253ddda2e32b1874/frontend/src/app/index.tsx#L51)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

Is this div necessary? 
</blockquote></details>

Yes. Only single node allowed under <Router>

---

*[frontend/src/app/actions/info.ts, line 17 at r4](https://reviewable.io:443/reviews/zanata/zanata-mt/57#-L6YthZz5unwYKn93kmG:-L6Z65xe65jUidkfwqh9:b-5ubsfr) ([raw file](https://github.com/zanata/zanata-mt/blob/f2c0a32490ec5aed2f30e840253ddda2e32b1874/frontend/src/app/actions/info.ts#L17)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

We use a tuple type for actions that looks like `export type APITypes = [string|{}, string|{}, string|{}]` in [Zanata Platform PR 737](https://github.com/zanata/zanata-platform/pull/737/files#diff-328ae56e88f06e81ee08e844404fd6b0), defining each actions type individually like this seems like a good approach as well.
</blockquote></details>

Different way of doing the same thing :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/57)*

**Comment by seanf** [comment]
Reviewed 1 of 15 files at r6.
Review status: 67 of 77 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[frontend/src/tsconfig.json, line 9 at r4](https://reviewable.io:443/reviews/zanata/zanata-mt/57#-L6YyzbV3wvir3xy-nNb:-L6ZQafMfzSkx6dWuEx_:beumgat) ([raw file](https://github.com/zanata/zanata-mt/blob/f2c0a32490ec5aed2f30e840253ddda2e32b1874/frontend/src/tsconfig.json#L9)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Trying to target somewhat standard version. ESNext is nice but I think too new to and not stabilised yet. 
</blockquote></details>

I think it's too soon to assume that the browser supports ES.next anyway.

This option is just about the transpilation target.

---

*[frontend/src/webpack.config.js, line 122 at r4](https://reviewable.io:443/reviews/zanata/zanata-mt/57#-L6Yzc3w52MI-PaU9N7g:-L6ZRx2yc_61K2ISiMfj:b-8fx2u7) ([raw file](https://github.com/zanata/zanata-mt/blob/f2c0a32490ec5aed2f30e840253ddda2e32b1874/frontend/src/webpack.config.js#L122)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Possibly. I think best to have it as separate PR unless I can migrate to webpack 4 in time. 
</blockquote></details>

:+1: 

---

*[frontend/src/app/index.tsx, line 51 at r4](https://reviewable.io:443/reviews/zanata/zanata-mt/57#-L6Z-LDF706FmUeAszso:-L6ZPSYk0tkGhCAW6j58:bopjc2v) ([raw file](https://github.com/zanata/zanata-mt/blob/f2c0a32490ec5aed2f30e840253ddda2e32b1874/frontend/src/app/index.tsx#L51)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Yes. Only single node allowed under <Router>
</blockquote></details>

under what? Router?

Can we use the new `<>` `</>` fragment feature here (React 16)?

---

*[frontend/src/app/actions/common.ts, line 12 at r6](https://reviewable.io:443/reviews/zanata/zanata-mt/57#-L6ZRN5xJOt_6GB3xbR4:-L6ZRN5xJOt_6GB3xbR5:b-567jtt) ([raw file](https://github.com/zanata/zanata-mt/blob/8ad21d9fc996bf6c84c859254fae373bd4432d9d/frontend/src/app/actions/common.ts#L12)):*
> ```XML
> export const buildAPIRequest =
>         (endpoint: string, method: HTTPVerb,
>          headers: { [propName: string]: string }, types: Types , body: FormData) => {
> ```

I think it would be better as `body?: FormData`, so that callers aren't forced to pass in `undefined` for that parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/57)*

**Comment by efloden** [comment]
Reviewed 13 of 15 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/57)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[frontend/src/app/index.tsx, line 51 at r4](https://reviewable.io:443/reviews/zanata/zanata-mt/57#-L6Z-LDF706FmUeAszso:-L6ZSsj8-WxF5nVyB7-i:b-ecoiml) ([raw file](https://github.com/zanata/zanata-mt/blob/f2c0a32490ec5aed2f30e840253ddda2e32b1874/frontend/src/app/index.tsx#L51)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

under what? Router?

Can we use the new `<>` `</>` fragment feature here (React 16)?
</blockquote></details>

yeah, under Router. Using <> 

---

*[frontend/src/app/actions/common.ts, line 12 at r6](https://reviewable.io:443/reviews/zanata/zanata-mt/57#-L6ZRN5xJOt_6GB3xbR4:-L6_EW56cJMuXR1NneNo:b-896fix) ([raw file](https://github.com/zanata/zanata-mt/blob/8ad21d9fc996bf6c84c859254fae373bd4432d9d/frontend/src/app/actions/common.ts#L12)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I think it would be better as `body?: FormData`, so that callers aren't forced to pass in `undefined` for that parameter.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/57)*

**Comment by efloden** [comment]
Reviewed 4 of 4 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-mt/57)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[frontend/src/app/index.tsx, line 51 at r4](https://reviewable.io:443/reviews/zanata/zanata-mt/57#-L6Z-LDF706FmUeAszso:-L6_q5JI8ZEuaD_uv_5B:b-8fx2u7) ([raw file](https://github.com/zanata/zanata-mt/blob/f2c0a32490ec5aed2f30e840253ddda2e32b1874/frontend/src/app/index.tsx#L51)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

yeah, under Router. Using <> 
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/57)*

**Comment by efloden** [comment]
Reviewed 7 of 7 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/57)*

**Pull request merged**
