### PR TITLE
Multi module

### PR DESCRIPTION
**Pull request by aeng**
Restructure mt into multi modole project

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/22)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 38 of 331 files at r1.
Review status: 24 of 170 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 6 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/22#-KnWa1TBuXfo1lGhM_cL:-KnWa1TBuXfo1lGhM_cM:b-4fbo5a) ([raw file](https://github.com/zanata/zanata-mt/blob/1f64857ac581699de8d01a85cd81044618128dd2/README.md#L6)):*
> ```Markdown
> - Package: `mvn clean package` (build and package war file)
> - Docker build: Go to `server` directory, run `mvn docker:build -DskipTests` (build docker image named zanataMT)
> - Start docker: `mvn docker:start` (This will start docker **zanataMT** and postgresql **zanataMTDB**)
> ```

does the last 3 commands need to be run under server directory?

---

*[frontend/pom.xml, line 112 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/22#-KnWaWg2NZqtWwQJzbyA:-KnWaWg2NZqtWwQJzbyB:b-e6w0ov) ([raw file](https://github.com/zanata/zanata-mt/blob/1f64857ac581699de8d01a85cd81044618128dd2/frontend/pom.xml#L112)):*
> ```XML
>                   <include>editor.min.js</include>
>                   <include>editor.css</include>
>                   <include>editor.css.map</include>
> ```

Don't think we need to split into editor, frontend and legacy here

---

*[frontend/src/.eslintrc, line 11 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/22#-KnWb56IVdypvYlQzB9E:-KnWb56IVdypvYlQzB9F:b-cnh6ul) ([raw file](https://github.com/zanata/zanata-mt/blob/1f64857ac581699de8d01a85cd81044618128dd2/frontend/src/.eslintrc#L11)):*
> ```
>   # TODO migrate frontend to have all double-quotes and reactivate this rule
>   jsx-quotes:
> #    - 2              # Error to enforce compliance.
> ```

We might start enforcing this since this is a new project

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/22)*

**Comment by aeng** [comment]
Review status: 24 of 170 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 6 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/22#-KnWa1TBuXfo1lGhM_cL:-KnWeg19JKMxMq9sB82q:bb77ufg) ([raw file](https://github.com/zanata/zanata-mt/blob/1f64857ac581699de8d01a85cd81044618128dd2/README.md#L6)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

does the last 3 commands need to be run under server directory?
</blockquote></details>

Yes.

---

*[frontend/pom.xml, line 112 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/22#-KnWaWg2NZqtWwQJzbyA:-KnWdwFt2q1pnuDrVx3_:b-cr13cv) ([raw file](https://github.com/zanata/zanata-mt/blob/1f64857ac581699de8d01a85cd81044618128dd2/frontend/pom.xml#L112)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Don't think we need to split into editor, frontend and legacy here
</blockquote></details>

Frontend is empty at the moment and this is not working at the moment, just a copy from zanata-frontend.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/22)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 3 of 3 files at r3.
Review status: 24 of 170 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/22#-:-KnWxoZCpQT-BX3SxVMA:b49ms4)*

**Comment by aeng** [comment]
@huangp you think we need QA for this?

**Comment by huangp** [comment]
Probably just run through the build and verify it still works.

**Comment by aeng** [comment]
ok.

**Comment by djansen-redhat** [comment]
✅ verified

**Pull request merged**
