### PR TITLE
feat: add managed-platform deployment

### PR DESCRIPTION
**Pull request by aeng**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/33)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Jenkinsfile, line 161 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/33#-Kvj1aBEAntG7vd8Zzlb:-Kvj1aBFaaSIy0fHo4uZ:batbxbo) ([raw file](https://github.com/zanata/zanata-mt/blob/5160baa34ce56d355bd4ce55343f3e3e808f7cc1/Jenkinsfile#L161)):*
> ```Groovy
>                 },
>                 // New platform for Docker and Openshift deployment
>                 "DOCKER_BUILD_RELEASE2": {
> ```

Could we change all the *2 variable/method name to something like ManagedPlatform? It's hard to tell which is which

---

*[Jenkinsfile, line 217 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/33#-Kvj24KnOIP6JXA8wLtm:-Kvj24KnOIP6JXA8wLtn:b-e41f96) ([raw file](https://github.com/zanata/zanata-mt/blob/5160baa34ce56d355bd4ce55343f3e3e808f7cc1/Jenkinsfile#L217)):*
> ```Groovy
>      */
>     sh "curl -L https://repo1.maven.org/maven2/org/postgresql/postgresql/9.4.1212/postgresql-9.4.1212.jar > $DOCKER_WORKSPACE/postgresql-connector.jar"
>     def certName = 'rds-combined-ca-bundle.pem'
> ```

Will managed platform image has Red Hat internal CA imported? 

---

*[Jenkinsfile, line 240 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/33#-Kvj2jgYVTkUtulVoOxJ:-Kvj2jgYVTkUtulVoOxK:b-f69b1z) ([raw file](https://github.com/zanata/zanata-mt/blob/5160baa34ce56d355bd4ce55343f3e3e808f7cc1/Jenkinsfile#L240)):*
> ```Groovy
> 
>       echo "Remove local docker image $dockerImage:$version"
>       sh "docker rmi $dockerImage:$version; docker rmi $MT_DOCKER_REGISTRY_URL2/$dockerImage:$version; docker rmi $MT_DOCKER_REGISTRY_URL2/$dockerImage:latest"
> ```

If we could extract all the variables inside this function to be the function parameter, then we can just call the same function with different parameters to push to either openpass or managed platform (unless there is significant difference between the two blocks).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/33)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Jenkinsfile, line 217 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/33#-Kvj24KnOIP6JXA8wLtm:-Kvj7kJe6Y4MQFWF1vIb:b-7eo3i4) ([raw file](https://github.com/zanata/zanata-mt/blob/5160baa34ce56d355bd4ce55343f3e3e808f7cc1/Jenkinsfile#L217)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Will managed platform image has Red Hat internal CA imported? 
</blockquote></details>

The based image already configured for that. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/33)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Jenkinsfile, line 240 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/33#-Kvj2jgYVTkUtulVoOxJ:-Kvj8jjXi-OAi5YfKM4V:b-cu6ltf) ([raw file](https://github.com/zanata/zanata-mt/blob/5160baa34ce56d355bd4ce55343f3e3e808f7cc1/Jenkinsfile#L240)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

If we could extract all the variables inside this function to be the function parameter, then we can just call the same function with different parameters to push to either openpass or managed platform (unless there is significant difference between the two blocks).
</blockquote></details>

Ultimately we gonna have only 1 of them and I think its clearer to have them separate as it is now and just delete one of them when the time comes. There are few different steps in the method which makes it better just to have them separated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/33)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/33#-:-KwhgLrcPM3wr6BGNklg:b-ew2adl)*

**Pull request merged**
