### PR TITLE
refactor: use mariadb for persistance

### PR DESCRIPTION
**Pull request by aeng**
switch to mariaDB

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/3)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pom.xml, line 236 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/3#-KfPZlKlDRfcwep8dGtZ:-KfPZlKlDRfcwep8dGt_:bwhoefw) ([raw file](https://github.com/zanata/zanata-mt/blob/67983ad35f212b8228e267c6ab2cad0c80686598/pom.xml#L236)):*
> ```XML
>                 <ports>
>                   
>                   <port>3305:${mariadb.port}</port>
> ```

Why change 3306 to 3305?

---

*[docker/conf/zanata-mt-config.cli, line 18 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/3#-KfP_4Gj9aONPf5h0ViG:-KfP_4Gj9aONPf5h0ViH:b-9mvpvd) ([raw file](https://github.com/zanata/zanata-mt/blob/67983ad35f212b8228e267c6ab2cad0c80686598/docker/conf/zanata-mt-config.cli#L18)):*
> ```
>     driver-class-name="com.mysql.jdbc.Driver")
> 
> data-source add --name=zanataMTDatasource \
> ```

I thought you found a way of using standalone-openshift.xml as is by choosing your env vars carefully. In which case we wouldn't need the cli script to add all this stuff.

---

*[docker/conf/zanata-mt-config.cli, line 21 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/3#-KfP_MU8-Zw8i-_1kQ47:-KfP_MU937bAKbJxCT-6:b-lhmhnq) ([raw file](https://github.com/zanata/zanata-mt/blob/67983ad35f212b8228e267c6ab2cad0c80686598/docker/conf/zanata-mt-config.cli#L21)):*
> ```
>     --jndi-name=java:jboss/datasources/zanataMT \
>     --driver-name=mysql \
>     --connection-url=jdbc:mysql://${env.MARIADB_URL}:${env.MARIADB_PORT:}/${env.MARIADB_DATABASE:}?characterEncoding=UTF-8 \
> ```

We should make sure the database uses utf8m4b. Remember how silly mysql can be.

Not sure where this should be controlled though, perhaps like this:

Ref: https://hub.docker.com/_/mariadb/ "Configuration without a cnf file"

---

*[src/main/java/org/zanata/mt/dao/DocumentDAO.java, line 34 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/3#-KfPb0c8ijBCVZuJmM0A:-KfPb0c8ijBCVZuJmM0B:bp3lo6) ([raw file](https://github.com/zanata/zanata-mt/blob/67983ad35f212b8228e267c6ab2cad0c80686598/src/main/java/org/zanata/mt/dao/DocumentDAO.java#L34)):*
> ```Java
>         List<Document> documents = getEntityManager()
>             .createQuery("from Document where urlHash = :urlHash and srcLocale = :srcLocale and targetLocale = :targetLocale")
>             .setParameter("urlHash", urlHash)
> ```

We're hashing the URL now? Is it too long for mysql to index?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/3)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pom.xml, line 236 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/3#-KfPZlKlDRfcwep8dGtZ:-KfPhMf6fskaQDBxzLSA:blr6faj) ([raw file](https://github.com/zanata/zanata-mt/blob/67983ad35f212b8228e267c6ab2cad0c80686598/pom.xml#L236)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Why change 3306 to 3305?
</blockquote></details>

This is to map to host, my host has another mysql 3306 running, thats why map to 3305

---

*[docker/conf/zanata-mt-config.cli, line 18 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/3#-KfP_4Gj9aONPf5h0ViG:-KfPhVqq8XVGERZS-HVS:b-a7kwqp) ([raw file](https://github.com/zanata/zanata-mt/blob/67983ad35f212b8228e267c6ab2cad0c80686598/docker/conf/zanata-mt-config.cli#L18)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I thought you found a way of using standalone-openshift.xml as is by choosing your env vars carefully. In which case we wouldn't need the cli script to add all this stuff.
</blockquote></details>

Yes I did. This is just for non-openshift docker build, backup in-case we not using openshift. but im happy to remove it.

---

*[docker/conf/zanata-mt-config.cli, line 21 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/3#-KfP_MU8-Zw8i-_1kQ47:-KfPhmE0nQCwcA7G6j6H:b55xlz6) ([raw file](https://github.com/zanata/zanata-mt/blob/67983ad35f212b8228e267c6ab2cad0c80686598/docker/conf/zanata-mt-config.cli#L21)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

We should make sure the database uses utf8m4b. Remember how silly mysql can be.

Not sure where this should be controlled though, perhaps like this:

Ref: https://hub.docker.com/_/mariadb/ "Configuration without a cnf file"
</blockquote></details>

I will take a look into that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/3)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/org/zanata/mt/dao/DocumentDAO.java, line 34 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/3#-KfPb0c8ijBCVZuJmM0A:-KfPis_iz7MqEy7bEKcl:b1i9bz1) ([raw file](https://github.com/zanata/zanata-mt/blob/67983ad35f212b8228e267c6ab2cad0c80686598/src/main/java/org/zanata/mt/dao/DocumentDAO.java#L34)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

We're hashing the URL now? Is it too long for mysql to index?
</blockquote></details>

yes. too long to be index in mysql.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/3)*

**Comment by seanf** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docker/conf/zanata-mt-config.cli, line 18 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/3#-KfP_4Gj9aONPf5h0ViG:-KfPibCTIVHQs-LlE11T:bs64rx3) ([raw file](https://github.com/zanata/zanata-mt/blob/67983ad35f212b8228e267c6ab2cad0c80686598/docker/conf/zanata-mt-config.cli#L18)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Yes I did. This is just for non-openshift docker build, backup in-case we not using openshift. but im happy to remove it.
</blockquote></details>

No, that's fine, we do need a way of testing it locally, at least until we learn to use `oc cluster up`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/3#-:-KfPj3XlsA2vD4BcZXxm:bnfp4nl)*

**Pull request merged**
