### PR TITLE
feat(ZNTAMT-42): try locale without country code

### PR DESCRIPTION
**Pull request by seanf**
https://zanata.atlassian.net/browse/ZNTAMT-42

### CODE REVIEW

**Comment by spathare21** [comment]
As per ticket https://zanata.atlassian.net/browse/ZNTAMT-42 , MT should accept locale alias 
1. I have added locale aliases de-de, zh-hant, fr-fr but looks like it is not working if I pass 
like "toLocale": "de-de" 
2. Also "toLocale": "zh-Hant-TW" works but "toLocale": "zh-hant-tw" does not seem to work.

**Comment by seanf** [comment]
@spathare21 Can you give me more details please? How did you add locale aliases like fr-fr? Got any error messages or HTTP responses?

I can't reproduce this problem with a unit test, an integration test, nor with curl:

```
$ curl -i -H "Content-Type: application/json" -H "X-Auth-User: admin" -H "X-Auth-Token: secret" -d '{"contents": [{"type": "text/plain", "metadata": "meta", "value": "hello"}], "localeCode":"en-us", "url": "http://example.com/doc/1"}' 'http://localhost:8080/api/document/translate?toLocaleCode=fr' 
HTTP/1.1 200 OK
Connection: keep-alive
Vary: Origin
X-Powered-By: Undertow/1
Server: JBoss-EAP/7
Content-Type: application/json
Content-Length: 173
Date: Wed, 25 Jul 2018 05:09:00 GMT

{"url":"http://example.com/doc/1","contents":[{"value":"translated[网 hello 网]","type":"text/plain","metadata":"meta"}],"localeCode":"fr","backendId":"DEV","warnings":[]}
```

**Comment by spathare21** [comment]
@seanf  I have added aliases in Project settings -> langauges 
screenshot from 2018-07-25 10-58-18
and trying to request post req using postman 
http://localhost:8180/rest/mt/project/sachin21/version/gettext?docId=settings 
with body
{
"toLocale": "de-de",
"saveState": "Translated",
"overwriteFuzzy": true
}

**Comment by seanf** [comment]
@spathare21 That's a different sort of alias, because that's only in Zanata-Platform. This PR is about some built-in (non-customisable) aliases for MT - originally I implemented a database table with some extra locale aliases, but now it just removes the country code from requests if needed.

**Comment by spathare21** [comment]
@seanf ohh ok np then other looks good to me

**Comment by seanf** [comment]
@spathare21 The idea is that if a Zanata Platform project happens to use the locale **de-de** instead of **de**, it should still work with MT with this new feature.

**Pull request merged**
