### PR TITLE
Doc stats

### PR DESCRIPTION
**Pull request by aeng**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/13)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/org/zanata/mt/api/dto/TranslationRequestStatistics.java, line 11 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/13#-Kh5unYd6wY3RqWoyguw:-Kh5unYe5O1voiD_oUgC:bb7phvt) ([raw file](https://github.com/zanata/zanata-mt/blob/7124df60989147b4d30ed2f530ecf3287c016829/src/main/java/org/zanata/mt/api/dto/TranslationRequestStatistics.java#L11)):*
> ```Java
> 
> /**
>  * Statistics entry for single a single request with unique key
> ```

typo

---

*[src/main/java/org/zanata/mt/api/service/impl/DocumentResourceImpl.java, line 135 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/13#-Kh5vYyaRRMdO25Pr4t9:-Kh5vYyaRRMdO25Pr4tA:b1d2bqc) ([raw file](https://github.com/zanata/zanata-mt/blob/7124df60989147b4d30ed2f530ecf3287c016829/src/main/java/org/zanata/mt/api/service/impl/DocumentResourceImpl.java#L135)):*
> ```Java
>         } catch (BadRequestException e) {
>             return getUnexpectedError(e);
>         } catch (Exception e) {
> ```

You could use java 7's multiple exception catch feature to save some lines

---

*[src/main/java/org/zanata/mt/api/service/impl/DocumentResourceImpl.java, line 188 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/13#-Kh5xJBQjA0Pgs1KOuj2:-Kh5xJBRHI9jIMHGAVDt:b-p382fa) ([raw file](https://github.com/zanata/zanata-mt/blob/7124df60989147b4d30ed2f530ecf3287c016829/src/main/java/org/zanata/mt/api/service/impl/DocumentResourceImpl.java#L188)):*
> ```Java
>     }
> 
>     private Response getUnexpectedError(Exception e) {
> ```

You should use ExceptionMapper for this. It will make the code cleaner.

---

*[src/test/java/org/zanata/mt/api/service/LanguagesResourceTest.java, line 38 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/13#-Kh5wsibPBDM4jhtP0yj:-Kh5wsibPBDM4jhtP0yk:b8m2efs) ([raw file](https://github.com/zanata/zanata-mt/blob/7124df60989147b4d30ed2f530ecf3287c016829/src/test/java/org/zanata/mt/api/service/LanguagesResourceTest.java#L38)):*
> ```Java
>     public void testConstructor() {
>         LanguagesResource
>                 resource = new LanguagesResourceImpl();
> ```

Do you just want to increase coverage? This test is meaningless to me

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/13)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/org/zanata/mt/api/service/impl/DocumentResourceImpl.java, line 188 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/13#-Kh5xJBQjA0Pgs1KOuj2:-Kh60-LYl7MhbYrXmhv5:b-x64r21) ([raw file](https://github.com/zanata/zanata-mt/blob/7124df60989147b4d30ed2f530ecf3287c016829/src/main/java/org/zanata/mt/api/service/impl/DocumentResourceImpl.java#L188)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

You should use ExceptionMapper for this. It will make the code cleaner.
</blockquote></details>

On it...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/13)*

**Comment by aeng** [comment]
Review status: 17 of 39 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/org/zanata/mt/api/dto/TranslationRequestStatistics.java, line 11 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/13#-Kh5unYd6wY3RqWoyguw:-KhK-wLjsroTckdSAZCg:b-896fix) ([raw file](https://github.com/zanata/zanata-mt/blob/7124df60989147b4d30ed2f530ecf3287c016829/src/main/java/org/zanata/mt/api/dto/TranslationRequestStatistics.java#L11)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.

---

*[src/main/java/org/zanata/mt/api/service/impl/DocumentResourceImpl.java, line 135 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/13#-Kh5vYyaRRMdO25Pr4t9:-KhK-xeKxDZoRs-8xKm-:b-rqwwvz) ([raw file](https://github.com/zanata/zanata-mt/blob/7124df60989147b4d30ed2f530ecf3287c016829/src/main/java/org/zanata/mt/api/service/impl/DocumentResourceImpl.java#L135)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

You could use java 7's multiple exception catch feature to save some lines
</blockquote></details>

Done. Replaced with ExceptionMapper.

---

*[src/main/java/org/zanata/mt/api/service/impl/DocumentResourceImpl.java, line 188 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/13#-Kh5xJBQjA0Pgs1KOuj2:-KhK01fwfJR3ah7Fv589:b-rqwwvz) ([raw file](https://github.com/zanata/zanata-mt/blob/7124df60989147b4d30ed2f530ecf3287c016829/src/main/java/org/zanata/mt/api/service/impl/DocumentResourceImpl.java#L188)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

On it...
</blockquote></details>

Done. Replaced with ExceptionMapper.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/13)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 2 of 31 files at r1, 22 of 22 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/13#-:-KhK3SE15vRTBqEd0M9B:b49ms4)*

**Comment by huangp** [comment]
:lgtm:

---

Reviewed 2 of 31 files at r1, 15 of 15 files at r3.
Review status: 45 of 47 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/13#-:-KhKVFD4NztJ10BGEysM:bnfp4nl)*

**Comment by huangp** [comment]
Reviewed 1 of 2 files at r4.
Review status: 46 of 47 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/13)*

**Comment by djansen-redhat** [comment]
Looks good to me

**Pull request merged**
