### PR TITLE
refactor: restructure document-TF relationship

### PR DESCRIPTION
**Pull request by aeng**
Refactor Document->TF to one-to-many relationship.

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/18)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/org/zanata/mt/model/TextFlow.java, line 33 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/18#-KlLcbM_Xwbkf0mKdflx:-KlLcbM_Xwbkf0mKdfly:b-qriman) ([raw file](https://github.com/zanata/zanata-mt/blob/d3f1a33e4d7354f78d5f36f4149171304b4e4d83/src/main/java/org/zanata/mt/model/TextFlow.java#L33)):*
> ```Java
>     private static final long serialVersionUID = -4550040877568062431L;
> 
>     @NaturalId
> ```

Judging by the database baseline.sql, it looks like Natural Id would be a combination of document, contenthash and locale

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/18)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/org/zanata/mt/model/TextFlow.java, line 33 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/18#-KlLcbM_Xwbkf0mKdflx:-KlLqvI4YGCJK_5dKr10:b-ej8yrk) ([raw file](https://github.com/zanata/zanata-mt/blob/d3f1a33e4d7354f78d5f36f4149171304b4e4d83/src/main/java/org/zanata/mt/model/TextFlow.java#L33)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Judging by the database baseline.sql, it looks like Natural Id would be a combination of document, contenthash and locale
</blockquote></details>

Yes it is. And I have the annotation on the three fields.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/18)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/18#-:-KlLrNK-EWMysYQirYzA:b49ms4)*

**Comment by djansen-redhat** [comment]
Reviewed 19 of 21 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/18)*

**Comment by djansen-redhat** [comment]
Neat.

**Pull request merged**
