### PR TITLE
ZNTAMT-8 Google backend

### PR DESCRIPTION
**Pull request by huangp**
https://zanata.atlassian.net/browse/ZNTAMT-8

- Since google hasn't release a newer version, to test this PR, you will have to clone or download from https://github.com/GoogleCloudPlatform/google-cloud-java then run
```
mvn install -pl :google-cloud-translate -am  -DskipTests
```
to install the google snapshot version to local maven.

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/30)

### CODE REVIEW

**Comment by aeng** [comment]
@huangp the manual step to get the client will break the automate build process. Anyway to host ourselves before its release?

**Comment by huangp** [comment]
I will not merge this to master without having a proper version available. I just want to start the review process sooner. If we want to merge sooner, we will have to drop support of 'text' format translation from google and wait until the new version is out to update the code again.

**Comment by aeng** [comment]
Good point!

**Comment by aeng** [comment]
Reviewed 1 of 30 files at r1, 41 of 49 files at r2.
Review status: 42 of 49 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pom.xml, line 46 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-Kq5GxZ1pjOnIpdtyMHo:-Kq5GxZ1pjOnIpdtyMHp:b-stc5io) ([raw file](https://github.com/zanata/zanata-mt/blob/9f1ad5ea60e85704bed9707bee2090a6097e560f/pom.xml#L46)):*
> ```XML
>     <validation-api.version>1.1.0.Final</validation-api.version>
>     <hibernate.validator.version>5.3.4.Final</hibernate.validator.version>
>     <hibernate.version>5.0.10.Final</hibernate.version>
> ```

Any reason we downgrade the version?

---

*[README.md, line 25 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-Kq5IBPMPBKyTii4FShD:-Kq5IBPMPBKyTii4FShE:blbu45k) ([raw file](https://github.com/zanata/zanata-mt/blob/9f1ad5ea60e85704bed9707bee2090a6097e560f/README.md#L25)):*
> ```Markdown
> ### DEV mode
> 
> DEV mode is enabled when **ZANATA_MT_AZURE_KEY** or **GOOGLE_APPLICATION_CREDENTIALS** is not present in environment variable. The service will not use any paid service backend in this mode but will return wrapped string: 'translated[𠾴 string 𠾴]'.
> ```

I think we should stick with ZANATA_MT_GOOGLE_CREDENTIALS, the variable is used in openshift config too.

---

*[README.md, line 45 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-Kq5ITSePOFEAloYBiGf:-Kq5ITSePOFEAloYBiGg:b-es88k9) ([raw file](https://github.com/zanata/zanata-mt/blob/9f1ad5ea60e85704bed9707bee2090a6097e560f/README.md#L45)):*
> ```Markdown
> Subscription key for MS translators
> 
> ### `GOOGLE_APPLICATION_CREDENTIALS` (if this and AZURE key are empty, DEV mode will be enabled)
> ```

Again,  ZANATA_MT_GOOGLE_CREDENTIALS

---

*[server/pom.xml, line 118 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-Kq5IYA4KhJowh6b1Whu:-Kq5IYA4KhJowh6b1Whv:b-3hir2n) ([raw file](https://github.com/zanata/zanata-mt/blob/9f1ad5ea60e85704bed9707bee2090a6097e560f/server/pom.xml#L118)):*
> ```XML
>                   <ZANATA_MT_AZURE_KEY>${ZANATA_MT_AZURE_KEY}</ZANATA_MT_AZURE_KEY>
>                   
>                   <GOOGLE_APPLICATION_CREDENTIALS>/opt/jboss/google/zanata-mt-credential.json</GOOGLE_APPLICATION_CREDENTIALS>
> ```

 ZANATA_MT_GOOGLE_CREDENTIALS

---

*[server/pom.xml, line 141 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-Kq5IdD-ZzZVAmKCEPzF:-Kq5IdD-ZzZVAmKCEPzG:b-3hir2n) ([raw file](https://github.com/zanata/zanata-mt/blob/9f1ad5ea60e85704bed9707bee2090a6097e560f/server/pom.xml#L141)):*
> ```XML
>                 <volumes>
>                   <bind>
>                     ${GOOGLE_APPLICATION_CREDENTIALS}:/opt/jboss/google/zanata-mt-credential.json
> ```

 ZANATA_MT_GOOGLE_CREDENTIALS

---

*[server/rebuild.sh, line 32 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-Kq5IhuqwWvfEHy1H15_:-Kq5Ihur_HEzJGLH_ggl:b-3hir2n) ([raw file](https://github.com/zanata/zanata-mt/blob/9f1ad5ea60e85704bed9707bee2090a6097e560f/server/rebuild.sh#L32)):*
> ```Shell
> mvn docker:build -DskipTests
> mvn docker:start \
>  -DGOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_CREDENTIAL_FILE} \
> ```

 ZANATA_MT_GOOGLE_CREDENTIALS

---

*[server/src/main/java/org/zanata/mt/api/APIConstant.java, line 27 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-Kq5IpPQWU_Z2yHT6gAK:-Kq5IpPQWU_Z2yHT6gAL:b-3hir2n) ([raw file](https://github.com/zanata/zanata-mt/blob/9f1ad5ea60e85704bed9707bee2090a6097e560f/server/src/main/java/org/zanata/mt/api/APIConstant.java#L27)):*
> ```Java
>      * https://developers.google.com/identity/protocols/application-default-credentials#howtheywork
>      */
>     String GOOGLE_ADC = "GOOGLE_APPLICATION_CREDENTIALS";
> ```

 ZANATA_MT_GOOGLE_CREDENTIALS

---

*[server/src/main/java/org/zanata/mt/service/DocumentService.java, line 65 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-Kq5JvRxaw9AkM8gE5EF:-Kq5JvRxaw9AkM8gE5EG:b1djwd1) ([raw file](https://github.com/zanata/zanata-mt/blob/9f1ad5ea60e85704bed9707bee2090a6097e560f/server/src/main/java/org/zanata/mt/service/DocumentService.java#L65)):*
> ```Java
>     @TransactionAttribute
>     // TODO should not expose this method
>     public void merge(Document doc) {
> ```

Hide this method?

---

*[server/src/main/java/org/zanata/mt/service/PersistentTranslationService.java, line 311 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-Kq5KAOr4B2Hrm40jT9k:-Kq5KAOr4B2Hrm40jT9l:b-95v1qn) ([raw file](https://github.com/zanata/zanata-mt/blob/9f1ad5ea60e85704bed9707bee2090a6097e560f/server/src/main/java/org/zanata/mt/service/PersistentTranslationService.java#L311)):*
> ```Java
> 
> 
> //        List<TextFlowTarget> existingTfts =
> ```

Remove this unused block?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/30)*

**Comment by huangp** [comment]
Review status: 38 of 49 files reviewed at latest revision, 9 unresolved discussions.

---

*[pom.xml, line 46 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-Kq5GxZ1pjOnIpdtyMHo:-Kq5LDTTC-QuFyLiGj3v:b-jmxbit) ([raw file](https://github.com/zanata/zanata-mt/blob/9f1ad5ea60e85704bed9707bee2090a6097e560f/pom.xml#L46)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Any reason we downgrade the version?
</blockquote></details>

This is the version used in wildfly. When I try to debug a problem I found the source code didn't match. I think we should stick to the version offered in the app server.

---

*[README.md, line 25 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-Kq5IBPMPBKyTii4FShD:-Kq5LV-rQeBWxeocmaZR:bi8yv8v) ([raw file](https://github.com/zanata/zanata-mt/blob/9f1ad5ea60e85704bed9707bee2090a6097e560f/README.md#L25)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I think we should stick with ZANATA_MT_GOOGLE_CREDENTIALS, the variable is used in openshift config too.
</blockquote></details>

Google library will look for environment variable GOOGLE_APPLICATION_CREDENTIALS to perform its auth work. There is no way (unless you fork a process) to change environment variable at runtime.

---

*[server/src/main/java/org/zanata/mt/service/DocumentService.java, line 65 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-Kq5JvRxaw9AkM8gE5EF:-Kq5VWoZTGDzXg7a8qGe:bfb54rd) ([raw file](https://github.com/zanata/zanata-mt/blob/9f1ad5ea60e85704bed9707bee2090a6097e560f/server/src/main/java/org/zanata/mt/service/DocumentService.java#L65)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Hide this method?
</blockquote></details>

moved the method to documentService instead.

---

*[server/src/main/java/org/zanata/mt/service/PersistentTranslationService.java, line 311 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-Kq5KAOr4B2Hrm40jT9k:-Kq5VTo-2hrkmJS5ZHDi:b-896fix) ([raw file](https://github.com/zanata/zanata-mt/blob/9f1ad5ea60e85704bed9707bee2090a6097e560f/server/src/main/java/org/zanata/mt/service/PersistentTranslationService.java#L311)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Remove this unused block?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/30)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 4 of 49 files at r2, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-:-Kq5aXyQrR-7IpoiHmJJ:bnfp4nl)*

**Comment by aeng** [comment]
@huangp Should update the jenkinsfile to include zanata-mt-credential.json in the docker image as part of the build.

**Comment by huangp** [comment]
@aeng it is okay to merge now. I commented out the part that requiring newer google library. Will need to find a secure place to store the google credential file and download it when building docker image in jenkinsfile.

**Comment by aeng** [comment]
@huangp but the build still fails.. not triggered?

**Comment by huangp** [comment]
Findbugs error. Fixing now

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-:-Kq6jqH9TEIIFIMLSB7c:bnfp4nl)*

**Comment by aeng** [comment]
Reviewed 18 of 20 files at r5.
Review status: 55 of 57 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[server/src/main/java/org/zanata/mt/backend/google/GoogleTranslatorBackend.java, line 103 at r5](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-KqLYJizdqDv7aEj7WBo:-KqLYJj-nqBXmg3q8R0O:becsof1) ([raw file](https://github.com/zanata/zanata-mt/blob/58916c9766b4c77a525ac5672667b1a1cf70d68f/server/src/main/java/org/zanata/mt/backend/google/GoogleTranslatorBackend.java#L103)):*
> ```Java
>         options.add(Translate.TranslateOption.format(format));
>         // google can detect source locale if omitted
>         // TODO we should probably retrieve and cache a google supported language list and check if the given locale code is supported or not
> ```

So we are hardcoding it at the moment like MS?

---

*[server/src/main/java/org/zanata/mt/util/DTOUtil.java, line 20 at r5](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-KqLYgOwjouZV0qMdqPY:-KqLYgOwjouZV0qMdqPZ:bipeqo) ([raw file](https://github.com/zanata/zanata-mt/blob/58916c9766b4c77a525ac5672667b1a1cf70d68f/server/src/main/java/org/zanata/mt/util/DTOUtil.java#L20)):*
> ```Java
> import java.io.StringWriter;
> 
> @ApplicationScoped
> ```

Any reason to make this bean instead of static util class?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/30)*

**Comment by huangp** [comment]
Review status: 55 of 57 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[server/src/main/java/org/zanata/mt/backend/google/GoogleTranslatorBackend.java, line 103 at r5](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-KqLYJizdqDv7aEj7WBo:-KqLeXJ4Vdl8cQih7xyO:b-wophsy) ([raw file](https://github.com/zanata/zanata-mt/blob/58916c9766b4c77a525ac5672667b1a1cf70d68f/server/src/main/java/org/zanata/mt/backend/google/GoogleTranslatorBackend.java#L103)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

So we are hardcoding it at the moment like MS?
</blockquote></details>

Yes. When you specify an invalid locale, google returns a generic error (e.g. parsing en-us instead of en). Makes it very hard to diagnose error. I think we should get the list of languages (both for google and ms) and cache then. And then return meaningful message when the locale is not supported.

---

*[server/src/main/java/org/zanata/mt/util/DTOUtil.java, line 20 at r5](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-KqLYgOwjouZV0qMdqPY:-KqLe7YlfDdEaqUXjy_J:byalamk) ([raw file](https://github.com/zanata/zanata-mt/blob/58916c9766b4c77a525ac5672667b1a1cf70d68f/server/src/main/java/org/zanata/mt/util/DTOUtil.java#L20)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Any reason to make this bean instead of static util class?
</blockquote></details>

static util class can not be mocked (not without powermock). Google Translation object has private constructor. If I mock Translation object then it can't be converted to JSON or XML.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/30)*

**Comment by aeng** [comment]
Reviewed 1 of 20 files at r5.
Review status: 56 of 57 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[server/src/main/java/org/zanata/mt/backend/google/GoogleTranslatorBackend.java, line 103 at r5](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-KqLYJizdqDv7aEj7WBo:-KqLhKXaRUuWT8PO5IOL:btbh2k2) ([raw file](https://github.com/zanata/zanata-mt/blob/58916c9766b4c77a525ac5672667b1a1cf70d68f/server/src/main/java/org/zanata/mt/backend/google/GoogleTranslatorBackend.java#L103)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Yes. When you specify an invalid locale, google returns a generic error (e.g. parsing en-us instead of en). Makes it very hard to diagnose error. I think we should get the list of languages (both for google and ms) and cache then. And then return meaningful message when the locale is not supported.
</blockquote></details>

Agreed. Definately todo list.

---

*[server/src/main/java/org/zanata/mt/util/DTOUtil.java, line 20 at r5](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-KqLYgOwjouZV0qMdqPY:-KqLhQmaN3qnSrOt4WCz:bhy1q54) ([raw file](https://github.com/zanata/zanata-mt/blob/58916c9766b4c77a525ac5672667b1a1cf70d68f/server/src/main/java/org/zanata/mt/util/DTOUtil.java#L20)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

static util class can not be mocked (not without powermock). Google Translation object has private constructor. If I mock Translation object then it can't be converted to JSON or XML.
</blockquote></details>

Should we try not to mock util class?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/30)*

**Comment by huangp** [comment]
Review status: 56 of 57 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[server/src/main/java/org/zanata/mt/util/DTOUtil.java, line 20 at r5](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-KqLYgOwjouZV0qMdqPY:-KqLiykmC5YtWTZcW_lK:b-fnnyve) ([raw file](https://github.com/zanata/zanata-mt/blob/58916c9766b4c77a525ac5672667b1a1cf70d68f/server/src/main/java/org/zanata/mt/util/DTOUtil.java#L20)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Should we try not to mock util class?
</blockquote></details>

Then I will have to construct a google Translation object by hacking the private constructor. In my second last commit I use reflection to hack it but I think this way is cleaner.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/30)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 20 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-:-KqLk4674nE5BesSesNf:bnfp4nl)*

**Comment by djansen-redhat** [comment]
Empty credentials for Google does not allow dev mode
```
[INFO] DOCKER> [postgres:9.5] "zanataMTDB": Waited on tcp port '[/172.17.0.2:5432]' 4011 ms
14:18:23.647 DB> LOG:  incomplete startup packet
[ERROR] DOCKER> Error occurred during container startup, shutting down...
14:18:27.518 DB> LOG:  received smart shutdown request
[INFO] DOCKER> [postgres:9.5] "zanataMTDB": Stop and removed container 25f1bfb1a67f after 0 ms
[ERROR] DOCKER> I/O Error
[INFO] FAILURE build of project org.zanata.mt:mt-server
[INFO] Builder state: blocked=0 finished=1 ready-or-running=0 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.142 s (Wall Clock)
[INFO] Finished at: 2017-08-03T14:18:28+10:00
[INFO] Final Memory: 27M/382M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.16.8:start (default-cli) on project mt-server: I/O Error: Unable to create container for [zanata/zanata-mt:latest]: create ${GOOGLE_APPLICATION_CREDENTIALS}: "${GOOGLE_APPLICATION_CREDENTIALS}" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed (Internal Server Error: 500) -> [Help 1]
```

**Comment by djansen-redhat** [comment]
Docs should be clear that the Google credentials variable is a _file_

**Comment by djansen-redhat** [comment]
When running with GOOGLE_APPLICATION_CREDENTIALS only:
```
15:02:27.113 WF> 05:02:27,111 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 63) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./ROOT: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./ROOT: java.lang.RuntimeException: org.zanata.mt.exception.ZanataMTException: Missing system properties of ZANATA_MT_AZURE_KEY
```

**Comment by huangp** [comment]
It's the in the README.md ```Location to the Google service account credential json file```

**Comment by huangp** [comment]
Do we have a requirement to allow only one MT provider to be used? @aeng e.g. not providing a google credential or MS credential and it automatically fall back to the only provider? At the moment, you either provide both or none (become dev mode)

**Comment by djansen-redhat** [comment]
@huangp hah, I didn't even see that section 😕

**Comment by djansen-redhat** [comment]
@aeng @huangp my understanding of the spec `Requestor should be able to select different type of backend`is that a) the system can provide 1-n backends b) the requester can query those backends and c) the user can then specify the desired backend

**Comment by djansen-redhat** [comment]
`http://localhost:8080/api/backend/attribution?id=google`
500 internal server error
```
13:46:28.752 WF> 03:46:28,748 ERROR [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-12) RESTEASY002005: Failed executing GET /backend/attribution: org.jboss.resteasy.core.NoMessageBodyWriterFoundFailure: Could not find MessageBodyWriter for response object of type: org.zanata.mt.api.dto.APIResponse of media type: image/png
```

**Comment by djansen-redhat** [comment]
`http://localhost:8080/api/document/translate?toLocaleCode=es`
with body
`{ "url":"http://redhat.com",  "localeCode":"en-US", "backendId":"meow", "contents":[{"type":"text/plain", "value":"Horizon: Zero Dawn", "metadata":""}] }`
results in 500 internal server error
> 03:50:08,883 ERROR [io.undertow.request] (default task-13) UT005023: Exception handling request to /api/document/translate: org.jboss.resteasy.spi.UnhandledException: javax.ejb.EJBTransactionRolledbackException: Error getting token:Unauthorized

Should be unknown backendId.

**Comment by djansen-redhat** [comment]
✖️ `http://localhost:8080/api/document/translate?toLocaleCode=es` will not work without providing the user/token for dev.
The user/token are provided as part of the request header (X-Auth-User/Token). I don't understand how a user provides these for the Google backend, when it's a private keyfile that's in use.

**Comment by huangp** [comment]
User provided credentials are for us to authenticate. e.g. if you don't know the username and token, you can't make any request. We (with system admin hat on) set up the google and MS credential ourselves when we install/deploy the app. Users do not need to know or provide MS or google credential.

**Comment by djansen-redhat** [comment]
Test:
- [ ] Google backed works
- [ ] MS backend (still) works
- [ ] Dev backend if neither of the above are enabled
- [ ] In the DB, MS=/=GOOGLE=/=DEV
- [ ] Google attrib image shows
- [ ] Query for backends (api/backend)

**Comment by djansen-redhat** [comment]
@huangp running `mvn docker:start -DZANATA_MT_AZURE_KEY=(key)` results in a _directory_ being copied in place of an empty file, with server/src/main/java/org/zanata/mt/backend/google/GoogleCredential.java:101 reporting an `IOException: Is a directory`

**Comment by huangp** [comment]
changed to not throw exception when the file can not be read

**Comment by djansen-redhat** [comment]
- [ ] `mvn docker:start -DZANATA_MT_AZURE_KEY=(key)` results in a start failure: 
> [ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.16.8:start (default-cli) on project mt-server: I/O Error: Unable to create container for [zanata/zanata-mt:latest]: create ${GOOGLE_APPLICATION_CREDENTIALS}: "${GOOGLE_APPLICATION_CREDENTIALS}" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intented to pass a host directory, use absolute path (Internal Server Error: 500) -> [Help 1]

- [ ] `mvn docker:start -DZANATA_MT_AZURE_KEY=(key) -DGOOGLE_APPLICATION_CREDENTIALS=/tmp/null.json` doesn't fail the check in GoogleCredential.java:63, so an empty file is copied, which results in
> 06:08:41,075 ERROR [org.jboss.as.ejb3.invocation] (default task-1) WFLYEJB0034: EJB Invocation failed on component PersistentTranslationService for method public java.util.List org.zanata.mt.service.PersistentTranslationService.translate(org.zanata.mt.model.Document,java.util.List,org.zanata.mt.model.Locale,org.zanata.mt.model.Locale,org.zanata.mt.model.BackendID,javax.ws.rs.core.MediaType,java.util.Optional) throws javax.ws.rs.BadRequestException,org.zanata.mt.exception.ZanataMTException: javax.ejb.EJBTransactionRolledbackException: Unable to get translations from Google API
...
Caused by: org.zanata.mt.exception.ZanataMTException: Unable to get translations from Google API
	at org.zanata.mt.backend.google.GoogleTranslatorBackend.translate(GoogleTranslatorBackend.java:111)
	at org.zanata.mt.service.PersistentTranslationService.translate(PersistentTranslationService.java:169)
...
Caused by: com.google.cloud.translate.TranslateException: The request is missing a valid API key.

**Comment by djansen-redhat** [comment]
- [ ] Bad cred file/azure key result in 500 error (should be 403 unauthorized)

**Comment by huangp** [comment]
Fixed point 1 (missing google credential file)
I can't reproduce point 2. I will get
```
{
    "status": 501,
    "title": "Error: backendId google not available",
    "details": null,
    "timestamp": "11-08-2017 00:37:44+0000"
}
```
in response if the cred file is empty.

**Comment by djansen-redhat** [comment]
@huangp `mvn docker:start -DZANATA_MT_AZURE_KEY=$key` still creates a bad cred file, so api/backend gives both MS and GOOGLE but the latter responds with bad api key.

**Comment by huangp** [comment]
Try again now

**Comment by djansen-redhat** [comment]
> Failed tests:   testAvailableProviders(org.zanata.mt.service.ConfigurationServiceTest): (..)
>   testConstructor(org.zanata.mt.service.ConfigurationServiceTest): expected:</tmp/junit3910506676434489888/junit3350913927392068276.tmp> but was:< null>

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r6, 2 of 10 files at r7, 12 of 20 files at r8, 7 of 8 files at r10, 1 of 1 files at r11, 1 of 2 files at r12, 2 of 2 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/30#-:-Ks1mn3mysk94V3BQjdC:bnfp4nl)*

**Pull request merged**
