### PR TITLE
ZNTAMT-15 tracking MT usage

### PR DESCRIPTION
**Pull request by huangp**
- admin can update account
- user can query own stats for a time period

### CODE REVIEW

**Comment by seanf** [comment]
Review status: 7 of 37 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[mt-data/src/main/java/org/zanata/magpie/util/CountUtil.java, line 96 at r2](https://reviewable.io/reviews/zanata/zanata-mt/67#-LDoRfrj8HyG2me4OA8O:-LDoRfrj8HyG2me4OA8P:b-o5nplc) ([raw file](https://github.com/zanata/zanata-mt/blob/474872edbc687213aec93b3c603f0d8c6c9a3787/mt-data/src/main/java/org/zanata/magpie/util/CountUtil.java#L96)):*
> ```Java
>     /**
>      * Count the characters in a string taking into account the locale.
>      * See https://stackoverflow.com/a/6846155/345718
> ```

It seems that this BreakIterator count disagrees with String.codePointCount, although I don't understand why that is. Do you?


In any case, Google charges by the locale-independent Unicode code point: https://cloud.google.com/translate/pricing - I suspect most of them would do the same.

Yep, it looks like MS is the same: https://www.microsoft.com/en-us/translator/faq.aspx?5e97a3b3-b121-4b87-ae3a-eac14c59717f=True

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/67)*

**Comment by seanf** [comment]
Review status: 28 of 38 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[common/src/main/java/org/zanata/magpie/api/service/ReportingResource.java, line 55 at r3](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEJ5uN9BYBT7Iv3MXUD:-LEJ5uN9BYBT7Iv3MXUE:blehsu4) ([raw file](https://github.com/zanata/zanata-mt/blob/5f7fd717737f42767dba111fe0e6729bee633ab9/common/src/main/java/org/zanata/magpie/api/service/ReportingResource.java#L55)):*
> ```Java
> 
>     /**
>      * Get the statistics for machine translation back end during a given date range.
> ```

"for requests by the current user."

Is that right?

---

*[mt-data/src/main/java/org/zanata/magpie/model/TextFlowMTRequest.java, line 82 at r3](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEJ6fvH0adIgOfRHqey:-LEJ6fvH0adIgOfRHqez:bjmm6py) ([raw file](https://github.com/zanata/zanata-mt/blob/5f7fd717737f42767dba111fe0e6729bee633ab9/mt-data/src/main/java/org/zanata/magpie/model/TextFlowMTRequest.java#L82)):*
> ```Java
> 
>     @NotNull
>     private Long charCount;
> ```

Any chance we could make these counts into `long`?

---

*[server/src/test/java/org/zanata/magpie/api/PayloadValidationInterceptorTest.java, line 68 at r3](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEJ5BVkARfg5ETC0eSt:-LEJ5BVkARfg5ETC0eSu:b-wo2vxi) ([raw file](https://github.com/zanata/zanata-mt/blob/5f7fd717737f42767dba111fe0e6729bee633ab9/server/src/test/java/org/zanata/magpie/api/PayloadValidationInterceptorTest.java#L68)):*
> ```Java
> 
>     @Test
>     public void badRequestIfAccountHasValidationError() throws Exception {
> ```

We should have another test where validation passes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/67)*

**Comment by huangp** [comment]
Review status: 28 of 38 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[common/src/main/java/org/zanata/magpie/api/service/ReportingResource.java, line 55 at r3](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEJ5uN9BYBT7Iv3MXUD:-LEMfiWo4a-8EiBLtqjN:byg0rkf) ([raw file](https://github.com/zanata/zanata-mt/blob/5f7fd717737f42767dba111fe0e6729bee633ab9/common/src/main/java/org/zanata/magpie/api/service/ReportingResource.java#L55)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

"for requests by the current user."

Is that right?
</blockquote></details>

Yes. doc updated.

---

*[mt-data/src/main/java/org/zanata/magpie/model/TextFlowMTRequest.java, line 82 at r3](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEJ6fvH0adIgOfRHqey:-LEMfupC3jCfCynYq8DB:b-ykwqz0) ([raw file](https://github.com/zanata/zanata-mt/blob/5f7fd717737f42767dba111fe0e6729bee633ab9/mt-data/src/main/java/org/zanata/magpie/model/TextFlowMTRequest.java#L82)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Any chance we could make these counts into `long`?
</blockquote></details>

long will default to 0. Then I will need to change the validation to ```@Min(1)```. But there won't be any constraint in the database.

---

*[server/src/test/java/org/zanata/magpie/api/PayloadValidationInterceptorTest.java, line 68 at r3](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEJ5BVkARfg5ETC0eSt:-LEMj2q17-_gjR5mGZN1:bb7f2mf) ([raw file](https://github.com/zanata/zanata-mt/blob/5f7fd717737f42767dba111fe0e6729bee633ab9/server/src/test/java/org/zanata/magpie/api/PayloadValidationInterceptorTest.java#L68)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

We should have another test where validation passes.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/67)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[business-svc/src/main/java/org/zanata/magpie/service/AccountService.java, line 114 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMtLAh-VWAEqXm1lNz:-LEMtLAh-VWAEqXm1lO-:b-1sfj82) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/business-svc/src/main/java/org/zanata/magpie/service/AccountService.java#L114)):*
> ```Java
>     }
> 
>     @TransactionAttribute
> ```

Just out of interest, why are we using EJB attributes for this sort of thing in MT, rather than DeltaSpike?

---

*[business-svc/src/main/java/org/zanata/magpie/service/ReportingService.java, line 66 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMtbdKEEu32LJ5BhDP:-LEMtbdKEEu32LJ5BhDQ:b-3qg4df) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/business-svc/src/main/java/org/zanata/magpie/service/ReportingService.java#L66)):*
> ```Java
>                 accountDAO.findAccountByUsername(username);
> 
>         if (account.isPresent()) {
> ```

Shouldn't we return 404 (or something which can be translated to 404, eg null) if not present?

---

*[business-svc/src/main/java/org/zanata/magpie/service/ReportingService.java, line 70 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMtx984g0h2yFTL64e:-LEMtx984g0h2yFTL64f:b-9ku0oq) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/business-svc/src/main/java/org/zanata/magpie/service/ReportingService.java#L70)):*
> ```Java
>             List<TextFlowMTRequest> requestsByDateRange =
>                         textFlowMTRequestDAO.getRequestsByDateRange(dateRange, account.get());
>             return requestsByDateRange.stream().map(r -> {
> ```

I think `req` or `request` might make the lambda a little easier to understand.

---

*[business-svc/src/main/java/org/zanata/magpie/service/ReportingService.java, line 73 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMtn28BdECJ5QxJV2W:-LEMtn2921NybD3dIVRH:b5l5hel) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/business-svc/src/main/java/org/zanata/magpie/service/ReportingService.java#L73)):*
> ```Java
>                 Document document = r.getDocument();
>                 LocaleCode fromLocaleCode = r.getDocument().getFromLocale().getLocaleCode();
>                 LocaleCode toLocaleCode = r.getDocument().getToLocale().getLocaleCode();
> ```

Better to use `document`, not `r.getDocument()`.

---

*[business-svc/src/test/java/org/zanata/magpie/service/ReportingServiceTest.java, line 56 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMuTIt1Nn0AI9GHzms:-LEMuTIt1Nn0AI9GHzmt:b-kdqsfa) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/business-svc/src/test/java/org/zanata/magpie/service/ReportingServiceTest.java#L56)):*
> ```Java
>                 service.getMTRequestStats("admin", dateRange);
> 
>         assertThat(requestStats).hasSize(1);
> ```

I think we need to check the results, not just count them.

---

*[business-svc/src/test/java/org/zanata/magpie/service/ReportingServiceTest.java, line 67 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMuQ60-99mQr1F-27S:-LEMuQ60-99mQr1F-27T:b-bo5mr8) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/business-svc/src/test/java/org/zanata/magpie/service/ReportingServiceTest.java#L67)):*
> ```Java
>                 DateRange.fromString("2018-05-01..2018-05-31"));
> 
>         assertThat(result).isEmpty();
> ```

A 404 seems like a more standard way of handling this case.

---

*[mt-data/src/main/java/org/zanata/magpie/liquibase/UpdateCharCountToTextFlow.java, line 75 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMvmpV1JZVpCK5EQhg:-LEMvmpV1JZVpCK5EQhh:bt1j9bt) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/mt-data/src/main/java/org/zanata/magpie/liquibase/UpdateCharCountToTextFlow.java#L75)):*
> ```Java
>             long totalRows;
>             String countSql =
>                     "select count(*) from TextFlow where charCount = 0";
> ```

I didn't really get your answer regarding `long` vs `Long`, but perhaps you could use -1 instead of 0, to indicate records which need migration.

---

*[mt-data/src/main/java/org/zanata/magpie/liquibase/UpdateCharCountToTextFlow.java, line 85 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMw3MM04VTEiHsngHy:-LEMw3MM04VTEiHsngHz:bdngxx5) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/mt-data/src/main/java/org/zanata/magpie/liquibase/UpdateCharCountToTextFlow.java#L85)):*
> ```Java
> 
>             String textFlowSql =
>                     "select tf.content, tf.charCount, loc.localeCode from TextFlow tf join Locale loc on tf.localeId = loc.id where tf.charCount = 0";
> ```

The capitalisation of charcount vs charCount seems to be inconsistent in various places.

---

*[mt-data/src/main/java/org/zanata/magpie/liquibase/UpdateCharCountToTextFlow.java, line 92 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMwPDaCHL_P-fw7P0i:-LEMwPDaCHL_P-fw7P0j:b-q4iki5) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/mt-data/src/main/java/org/zanata/magpie/liquibase/UpdateCharCountToTextFlow.java#L92)):*
> ```Java
>                     String locale = resultSet.getString(3);
>                     long charCount = CountUtil.countCharacters(content);
>                     resultSet.updateLong(2, charCount);
> ```

This JDBC code would be easier to understand if you defined constants for the column indexes, or used labels in the query and the get/update calls.

---

*[mt-data/src/main/java/org/zanata/magpie/liquibase/UpdateCharCountToTextFlow.java, line 94 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMxCs168iPEIH_QaIM:-LEMxCs264nr1RXWeJ6x:b-orbk8) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/mt-data/src/main/java/org/zanata/magpie/liquibase/UpdateCharCountToTextFlow.java#L94)):*
> ```Java
>                     resultSet.updateLong(2, charCount);
>                     resultSet.updateRow();
>                     if (++rowsUpdated % 10000 == 0) {
> ```

10_000 is slightly more readable.

---

*[mt-data/src/main/java/org/zanata/magpie/model/TextFlowMTRequest.java, line 82 at r3](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEJ6fvH0adIgOfRHqey:-LEMrtQiEm2iIgR4Xioz:bvu0pg6) ([raw file](https://github.com/zanata/zanata-mt/blob/5f7fd717737f42767dba111fe0e6729bee633ab9/mt-data/src/main/java/org/zanata/magpie/model/TextFlowMTRequest.java#L82)):*
Sorry, I don't really understand any of this.

> long will default to 0. 

When?

> Then I will need to change the validation to @Min(1). But there won't be any constraint in the database.

You mean add a validation here? What's the DB constraint?

---

*[server/src/main/java/org/zanata/magpie/api/PayloadValidationInterceptor.java, line 100 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMv8M50Ff4g_hS7_B6:-LEMv8M69ViR7wnw8Zlf:b-x23qpe) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/server/src/main/java/org/zanata/magpie/api/PayloadValidationInterceptor.java#L100)):*
> ```Java
>                 .getAnnotation(ValidatePayload.class);
>         if (validatePayload == null) {
>             validatePayload = invocation.getMethod().getAnnotation(ValidatePayload.class);
> ```

The usual convention is to check the lower level first (method), then fall back on the higher level (class). This lets you override higher-level settings with more specific settings at a lower level.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/67)*

**Comment by huangp** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[business-svc/src/main/java/org/zanata/magpie/service/AccountService.java, line 114 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMtLAh-VWAEqXm1lNz:-LENTGRI9t0tUx6uaI8q:bwukcpd) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/business-svc/src/main/java/org/zanata/magpie/service/AccountService.java#L114)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Just out of interest, why are we using EJB attributes for this sort of thing in MT, rather than DeltaSpike?
</blockquote></details>

Simple to use. Not having to add additional dependency

---

*[business-svc/src/main/java/org/zanata/magpie/service/ReportingService.java, line 66 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMtbdKEEu32LJ5BhDP:-LENTVUY1GDwPLH-QI86:b-vfuz1j) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/business-svc/src/main/java/org/zanata/magpie/service/ReportingService.java#L66)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Shouldn't we return 404 (or something which can be translated to 404, eg null) if not present?
</blockquote></details>

It's not possible for account to not present. We have security interceptor to ensure the username matches an account. I refactored it to be more clearer

---

*[business-svc/src/main/java/org/zanata/magpie/service/ReportingService.java, line 70 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMtx984g0h2yFTL64e:-LENU4K72tgo6wkUrkmC:bb7f2mf) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/business-svc/src/main/java/org/zanata/magpie/service/ReportingService.java#L70)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I think `req` or `request` might make the lambda a little easier to understand.
</blockquote></details>

done

---

*[business-svc/src/main/java/org/zanata/magpie/service/ReportingService.java, line 73 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMtn28BdECJ5QxJV2W:-LENU5VA2up9iJJ7F8gv:bb7f2mf) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/business-svc/src/main/java/org/zanata/magpie/service/ReportingService.java#L73)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Better to use `document`, not `r.getDocument()`.
</blockquote></details>

done

---

*[mt-data/src/main/java/org/zanata/magpie/liquibase/UpdateCharCountToTextFlow.java, line 75 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMvmpV1JZVpCK5EQhg:-LENmwOeDQrPDcmtG9h-:b-uqt4mz) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/mt-data/src/main/java/org/zanata/magpie/liquibase/UpdateCharCountToTextFlow.java#L75)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I didn't really get your answer regarding `long` vs `Long`, but perhaps you could use -1 instead of 0, to indicate records which need migration.
</blockquote></details>

in Java a long field will have default value of 0. If for any reason we didn't set the value, it will store 0 to database. There is no database constraint to prevent this. It's the same reason why id field is recommended to be Long not long. Setting database column default to -1 won't help if you forget to set your JPA entity's field

---

*[mt-data/src/main/java/org/zanata/magpie/liquibase/UpdateCharCountToTextFlow.java, line 85 at r4](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEMw3MM04VTEiHsngHy:-LENnXzNCtNf3UqcxnUi:b-effh0t) ([raw file](https://github.com/zanata/zanata-mt/blob/911ad87d2317717a726dc4f30142630a46e37db6/mt-data/src/main/java/org/zanata/magpie/liquibase/UpdateCharCountToTextFlow.java#L85)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

The capitalisation of charcount vs charCount seems to be inconsistent in various places.
</blockquote></details>

That's because postgres will use lowercase by default. I mentioned this in one of the retrospective. 

---

*[mt-data/src/main/java/org/zanata/magpie/model/TextFlowMTRequest.java, line 82 at r3](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEJ6fvH0adIgOfRHqey:-LENpLmGEQpOY1I_SRKo:b-pw0zqd) ([raw file](https://github.com/zanata/zanata-mt/blob/5f7fd717737f42767dba111fe0e6729bee633ab9/mt-data/src/main/java/org/zanata/magpie/model/TextFlowMTRequest.java#L82)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Sorry, I don't really understand any of this.

> long will default to 0. 

When?

> Then I will need to change the validation to @Min(1). But there won't be any constraint in the database.

You mean add a validation here? What's the DB constraint?
</blockquote></details>

When the field is not initialized properly. e.g. calling the no-arg constructor and then JPA will save the entity with 0 as the value (of cause it will fail other fields validation. But the idea is there). Validation means the ```@NotNull``` to ```@Min(1)``` change needed to prevent this from happening. DB has nullable = false constraint. But no minimum value constraint.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/67)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[mt-data/src/main/java/org/zanata/magpie/model/TextFlowMTRequest.java, line 82 at r3](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEJ6fvH0adIgOfRHqey:-LENxa9g965a-xwlkRXb:bvgkwk2) ([raw file](https://github.com/zanata/zanata-mt/blob/5f7fd717737f42767dba111fe0e6729bee633ab9/mt-data/src/main/java/org/zanata/magpie/model/TextFlowMTRequest.java#L82)):*
> When the field is not initialized properly. e.g. calling the no-arg constructor and then JPA will save the entity with 0 as the value (of cause it will fail other fields validation. But the idea is there). 

That won't be a problem if we make the zero-args constructor non-public.

> Validation means the @NotNull to @Min(1) change needed to prevent this from happening. DB has nullable = false constraint. But no minimum value constraint.

I don't think we will need Min(1) if we make the zero-args constructor non-public. Then there will only be two ways of constituting a TextFlowMTRequest - by calling the other constructor, or by reading an existing entity from the DB. 

And by using `long` the compiler will never allow us to assign null, which is better than a runtime validation.

---

*[mt-data/src/main/java/org/zanata/magpie/model/TextFlowMTRequest.java, line 89 at r5](https://reviewable.io/reviews/zanata/zanata-mt/67#-LENxMSz6q5Zo3RiO-ys:-LENxMSz6q5Zo3RiO-yt:b-euh7mt) ([raw file](https://github.com/zanata/zanata-mt/blob/6688c492013b133de9caab5519072524e98d5801/mt-data/src/main/java/org/zanata/magpie/model/TextFlowMTRequest.java#L89)):*
> ```Java
> 
>     public TextFlowMTRequest() {
>     }
> ```

We should make this constructor non-public. That will help to avoid putting invalid values into the object.

---

*[server/src/main/java/org/zanata/magpie/api/PayloadValidationInterceptor.java, line 48 at r5](https://reviewable.io/reviews/zanata/zanata-mt/67#-LENzUBp7og88MVOFDf4:-LENzUBp7og88MVOFDf5:bs5ah7z) ([raw file](https://github.com/zanata/zanata-mt/blob/6688c492013b133de9caab5519072524e98d5801/server/src/main/java/org/zanata/magpie/api/PayloadValidationInterceptor.java#L48)):*
> ```Java
> @Interceptor
> @ValidatePayload(Object.class)
> public class PayloadValidationInterceptor implements Serializable {
> ```

It might be a bit easier to get around the code base if ValidatePayload and the interceptor had similar names. Maybe ValidatePayloadInterceptor/Test?

---

*[server/src/main/java/org/zanata/magpie/api/PayloadValidationInterceptor.java, line 100 at r5](https://reviewable.io/reviews/zanata/zanata-mt/67#-LENz8imCdzKjof54gbe:-LENz8imCdzKjof54gbf:b-hq5cuy) ([raw file](https://github.com/zanata/zanata-mt/blob/6688c492013b133de9caab5519072524e98d5801/server/src/main/java/org/zanata/magpie/api/PayloadValidationInterceptor.java#L100)):*
> ```Java
>         if (validatePayload == null) {
>             validatePayload = invocation.getTarget().getClass()
>                     .getAnnotation(ValidatePayload.class);
> ```

How is this going to handle inheritance? Perhaps we should put a javadoc comment about the limitations on the annotation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/67)*

**Comment by huangp** [comment]
Review status: 34 of 38 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/org/zanata/magpie/api/PayloadValidationInterceptor.java, line 100 at r5](https://reviewable.io/reviews/zanata/zanata-mt/67#-LENz8imCdzKjof54gbe:-LEO8E9bAVlTJgSsq5tC:b-1oe2yu) ([raw file](https://github.com/zanata/zanata-mt/blob/6688c492013b133de9caab5519072524e98d5801/server/src/main/java/org/zanata/magpie/api/PayloadValidationInterceptor.java#L100)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

you are over engineering things. I will drop class level support and make this simpler
</blockquote></details>

looks like I can't do that. Added the comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/67)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[mt-data/src/main/java/org/zanata/magpie/model/TextFlowMTRequest.java, line 82 at r3](https://reviewable.io/reviews/zanata/zanata-mt/67#-LEJ6fvH0adIgOfRHqey:-LEO9ODmDVCY88SU58go:b-k2sxdb) ([raw file](https://github.com/zanata/zanata-mt/blob/5f7fd717737f42767dba111fe0e6729bee633ab9/mt-data/src/main/java/org/zanata/magpie/model/TextFlowMTRequest.java#L82)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

I am just using that no-arg constructor as an example. Not because it's the only potential cause of the problem. What if later on we add other constructors? What if we add setter methods to all the fields? What if we turn it to a bean and use it as DTO? The idea is to let the database help us prevent saving null to it if we ever forget to set value. id field is always Long not long for similar reason (and sure other reasons too). The benefit of changing it to long is not worth it in my opinion. Also not worth arguing further. Let me know if you insist.
</blockquote></details>

Fine, but please make the no-args constructor non-public. Can't hurt to let the compiler prevent the error in the first place.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/67)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/67#-:-LERZxhgC5VtEJRGXAxr:bnfp4nl)*

**Comment by djansen-redhat** [comment]
- [ ] Should prevent an empty request (Nullpointer on ReportingService:getMTRequestStats:62)

**Comment by djansen-redhat** [comment]
Verified

**Pull request merged**
