### PR TITLE
ZNTAMT-9 rename project to magpie

### PR DESCRIPTION
**Pull request by huangp**
- package name
- maven groupId
- variable names
- class names
- docker image/container names

Unchanged:
- github repository
- datasource name (openshift has its own values outside of scm)

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/48)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 164 of 480 files at r1, 312 of 315 files at r2.
Review status: 168 of 170 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/pom.xml, line 267 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/48#-L2X5bSqrP99_SB01I3l:-L2X5bSqrP99_SB01I3m:b-1glake) ([raw file](https://github.com/zanata/zanata-mt/blob/e7aa73f124b648518626e659eefdacf81ab10a96/server/pom.xml#L267)):*
> ```XML
>

**Comment by huangp** [comment]
Review status: 168 of 170 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/pom.xml, line 267 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/48#-L2X5bSqrP99_SB01I3l:-L2XOrx7JjzJk_IqHr6K:b-896fix) ([raw file](https://github.com/zanata/zanata-mt/blob/e7aa73f124b648518626e659eefdacf81ab10a96/server/pom.xml#L267)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

org.zanata.magpie...?
</blockquote></details>

Done.

---

*[server/src/main/java/org/zanata/magpie/api/APIConstant.java, line 13 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/48#-L2X5qlTtCSc3QFwdqic:-L2XOt6chnLygOZtX2JD:b-896fix) ([raw file](https://github.com/zanata/zanata-mt/blob/e7aa73f124b648518626e659eefdacf81ab10a96/server/src/main/java/org/zanata/magpie/api/APIConstant.java#L13)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

org.zanata.magpie...?
</blockquote></details>

Done.

---

*[server/src/main/java/org/zanata/magpie/backend/ms/MicrosoftTranslatorBackend.java, line 5 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/48#-L2X6fHaOuxaoKRhXrr3:-L2XOv4gQK4JJgP_n5pt:b-3pz5dt) ([raw file](https://github.com/zanata/zanata-mt/blob/f194c6c4ded0dbc2a37e19d37211fcc1e8cf3b0f/server/src/main/java/org/zanata/magpie/backend/ms/MicrosoftTranslatorBackend.java#L5)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Weird that the checkstyle didn't fail unused import. Should look at the config.
</blockquote></details>

Checkstyle won't check unused import. Findbugs or compiler warning does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/48)*

**Comment by aeng** [comment]
Reviewed 1 of 480 files at r1, 1 of 315 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/org/zanata/magpie/backend/ms/MicrosoftTranslatorBackend.java, line 5 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/48#-L2X6fHaOuxaoKRhXrr3:-L2XPV7dSn3RASzG6FES:b-uher2c) ([raw file](https://github.com/zanata/zanata-mt/blob/f194c6c4ded0dbc2a37e19d37211fcc1e8cf3b0f/server/src/main/java/org/zanata/magpie/backend/ms/MicrosoftTranslatorBackend.java#L5)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Checkstyle won't check unused import. Findbugs or compiler warning does.
</blockquote></details>

And we should have that right? or only in Zanata platform but not in magpie?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/48)*

**Comment by huangp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/src/main/java/org/zanata/magpie/backend/ms/MicrosoftTranslatorBackend.java, line 5 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/48#-L2X6fHaOuxaoKRhXrr3:-L2XXS8bdn2M4V6c5Xry:b-bobyn7) ([raw file](https://github.com/zanata/zanata-mt/blob/f194c6c4ded0dbc2a37e19d37211fcc1e8cf3b0f/server/src/main/java/org/zanata/magpie/backend/ms/MicrosoftTranslatorBackend.java#L5)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

And we should have that right? or only in Zanata platform but not in magpie?
</blockquote></details>

I think we should. But that should be done separately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/48)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/48#-:-L2XYCtx6jZwK9pVMkfn:bnfp4nl)*

**Pull request merged**
