### PR TITLE
prepare cluster webapp session

### PR DESCRIPTION
**Pull request by huangp**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/46)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/46#-:-L-TvBq35c7MZi3sXtNm:bnfp4nl)*

**Comment by aeng** [comment]
@huangp with the dev localhost wildfly, do we use the HA too?

**Comment by huangp** [comment]
changed to use standalone-full-ha.xml

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/46#-:-L-USNT1J876HXUlzcgj:bnfp4nl)*

**Pull request merged**
