### PR TITLE
feat: locale mapping for MS backend

### PR DESCRIPTION
**Pull request by aeng**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-mt/4)

### CODE REVIEW

**Comment by seanf** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/org/zanata/mt/api/dto/LocaleId.java, line 26 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/4#-Kfsa-HhhUvWsMb-e0f6:-Kfsa-HhhUvWsMb-e0f7:b-j0pofq) ([raw file](https://github.com/zanata/zanata-mt/blob/9839173aac2de06fce7527dc984bd694a9ef371d/src/main/java/org/zanata/mt/api/dto/LocaleId.java#L26)):*
> ```Java
>     public static final LocaleId RU = new LocaleId("ru");
>     public static final LocaleId ZH_HANS = new LocaleId("zh-hans");
>     public static final LocaleId ZH_HANT = new LocaleId("zh-hant");
> ```

I think we should introduce another class like MSLocaleID for the mapped locales. Using LocaleId for both concepts could lead to confusion (and bugs).

---

*[src/main/java/org/zanata/mt/servlet/JavaMelodyFilter.java, line 15 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/4#-Kfsa6GIoxv_YWx6lkEF:-Kfsa6GJEmNDddKbD7il:b-iplgzy) ([raw file](https://github.com/zanata/zanata-mt/blob/9839173aac2de06fce7527dc984bd694a9ef371d/src/main/java/org/zanata/mt/servlet/JavaMelodyFilter.java#L15)):*
> ```Java
> /**
>  * Overrides JavaMelody MonitoringFilter so that only admin users can
>  * access the JavaMelody console.
> ```

There doesn't seem to be credential checking, for admin or otherwise. Unless that's handled by another, earlier, servlet filter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/4)*

**Comment by aeng** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/org/zanata/mt/servlet/JavaMelodyFilter.java, line 15 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/4#-Kfsa6GIoxv_YWx6lkEF:-Kfsf3cAVsJbuVM3IOg3:b-k0v5l1) ([raw file](https://github.com/zanata/zanata-mt/blob/9839173aac2de06fce7527dc984bd694a9ef371d/src/main/java/org/zanata/mt/servlet/JavaMelodyFilter.java#L15)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

There doesn't seem to be credential checking, for admin or otherwise. Unless that's handled by another, earlier, servlet filter?
</blockquote></details>

Plan to do it in seperate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/4)*

**Comment by seanf** [comment]
Reviewed 2 of 19 files at r1, 4 of 5 files at r2.
Review status: 6 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/org/zanata/mt/backend/ms/MicrosoftTranslatorBackend.java, line 123 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/4#-KftY9TtMjgbZum1AzTH:-KftY9TtMjgbZum1AzTI:bjdlcgo) ([raw file](https://github.com/zanata/zanata-mt/blob/3b088e8e6e8422c85c0f8afe668c2b2cbdd4be8d/src/main/java/org/zanata/mt/backend/ms/MicrosoftTranslatorBackend.java#L123)):*
> ```Java
>     }
> 
>     public LocaleId getMappedLocale(LocaleId localeId) {
> ```

We shouldn't use LocaleId to represent both mapped and unmapped locales. We might need to introduce another interface (implemented by MSLocaleCode) to keep it backend-agnostic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/4)*

**Comment by seanf** [comment]
Review status: 6 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/org/zanata/mt/backend/ms/MicrosoftTranslatorBackend.java, line 125 at r2](https://reviewable.io:443/reviews/zanata/zanata-mt/4#-KftZbHLXVCEiLBJciv3:-KftZbHLXVCEiLBJciv4:b-kdzlzm) ([raw file](https://github.com/zanata/zanata-mt/blob/3b088e8e6e8422c85c0f8afe668c2b2cbdd4be8d/src/main/java/org/zanata/mt/backend/ms/MicrosoftTranslatorBackend.java#L125)):*
> ```Java
>     public LocaleId getMappedLocale(LocaleId localeId) {
>         MSLocaleCode from = new MSLocaleCode(localeId);
>         return LOCALE_MAP.getOrDefault(from, localeId);
> ```

We could use Java 8 Map's computeIfAbsent method here. We'll need to preload the map with the exceptions (mappings) at init time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/4)*

**Comment by huangp** [comment]
without too much knowledge in the code. This :lgtm: 

---

Reviewed 11 of 19 files at r1, 1 of 5 files at r2, 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/org/zanata/mt/backend/BackendLocaleCode.java, line 5 at r3](https://reviewable.io:443/reviews/zanata/zanata-mt/4#-KftkM2ua2ozzJ_zrlyw:-KftkM2ua2ozzJ_zrlyx:bijb3pz) ([raw file](https://github.com/zanata/zanata-mt/blob/2e92295e9516777e3c8eff700e411961fbc8b3ca/src/main/java/org/zanata/mt/backend/BackendLocaleCode.java#L5)):*
> ```Java
> import java.io.Serializable;
> 
> /**
> ```

Can we have some javadoc for this class?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/4#-:-KftyjORDz4lw7VEyhQI:bar419r)*

**Pull request merged**
