### PR TITLE
chore: convert to sass

### PR DESCRIPTION
**Pull request by aeng**

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +(No QA \(2nd vote\)) 

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/58#-:-L7NWesPHyBNqock6evS:b-lqxfl3)*

**Comment by seanf** [comment]
I think @djansen-redhat wanted to take a look at this.

**Comment by huangp** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/58#-:-L7Rfqd2CjUFxXG4XyCS:bnfp4nl)*

**Comment by djansen-redhat** [comment]
Should $server/ include a reference to '/health'?

This is otherwise fine.

**Comment by aeng** [comment]
The /health page is mainly for external query of the status for service. Dont think we need to have a link to it.

**Pull request merged**
