### PR TITLE
fix(ZNTAMT-20): Allow user setting of default provider

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA: https://zanata.atlassian.net/browse/ZNTAMT-20

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/pom.xml, line 157 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/59#-L7XBXX2Fsn_ck_jy6kR:-L7XBXX2Fsn_ck_jy6kS:b689v0c) ([raw file](https://github.com/zanata/zanata-mt/blob/9c953117620c60748526b21f7363abaeac945477/server/pom.xml#L157)):*
> ```XML
>                     <MT_API_ID>devID</MT_API_ID>
>                     <MT_API_KEY>devKEY</MT_API_KEY>
> 		    <DEFAULT_TRANSLATION_PROVIDER>${DEFAULT_TRANSLATION_PROVIDER}</DEFAULT_TRANSLATION_PROVIDER>
> ```

are these tab characters?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/59)*

**Comment by djansen-redhat** [comment]
*[server/pom.xml, line 157 at r1](https://reviewable.io:443/reviews/zanata/zanata-mt/59#-L7XBXX2Fsn_ck_jy6kR:-L7XEYmukDF320OyTHmu:bo4t3qh) ([raw file](https://github.com/zanata/zanata-mt/blob/9c953117620c60748526b21f7363abaeac945477/server/pom.xml#L157)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

are these tab characters?
</blockquote></details>

Oops - fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/59)*

**Comment by huangp** [comment]
-(Awaiting review) +Reviewed +(No QA \(1st vote\)) 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/59#-:-L7XR3SnkLi3e5KkKnzq:bwcpy5z)*

**Comment by djansen-redhat** [comment]
I think my setting of skiptests is invalid...

**Comment by djansen-redhat** [comment]
Ok @huangp I fixed them issues and it's back on review

**Comment by huangp** [comment]
-(Awaiting review) +Reviewed 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-mt/59#-:-L7g1RAMx8gb1gISfSRr:b-nl5gbj)*

**Pull request merged**
